name: CI
'on': push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
        env:
          BROWSER: 'chrome'
      - run: npx semantic-release
        env:
          CI: 'true'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
